name: Build LaTeX PDF

on:
  push:
    paths:
      - 'main.tex'
      - '.github/workflows/latex-pdf.yml'
  pull_request:
    paths:
      - 'main.tex'
      - '.github/workflows/latex-pdf.yml'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }} ${{ github.event.head_commit.message }}
          tag_name: ${{ github.ref_name }}
          files: main.pdf